export const cachorro: any[] = [
  "Sem Raça Definida (SRD)",
  "Afegão",
  "Afghan Hound",
  "Affenpinscher",
  "Airedale Terrier",
  "Akita Americano",
  "Akita Inu",
  "Akita Japonês",
  "Alano Espanhol",
  "American Staffordshire Terrier",
  "American Water Spaniel",
  "Barbet",
  "Basenji",
  "Basset Azul da Gasconha",
  "Basset Fulvo da Bretanha",
  "Basset Hound",
  "Beagle",
  "Beagle Harrier",
  "Bearded Collie",
  "Bedlington Terrier",
  "Bernese Mountain Dog",
  "Bichon Bolonhês",
  "Bichon Havanês",
  "Bichon Frisé",
  "Bichon Maltês",
  "Bloodhound",
  "Boiadeiro Australiano",
  "Boiadeiro Bernês",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Boxer",
  "Bull Terrier",
  "Buldogue",
  "Bulldog Inglês",
  "Buldogue",
  "Bulldog Francês",
  "Bullmastiff",
  "Bulmastife",
  "Cairn Terrier",
  "Cane Corso",
  "Cão de Água Português",
  "Cão de Crista Chinês",
  "Cão de Montanha dos Pirinéus",
  "Cão lobo checoslovaco",
  "Cão da Groenlândia",
  "Caniche",
  "Poodle",
  "Cavalier King Charles Spaniel",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chow Chow",
  "Cirneco do Etna",
  "Cocker Spaniel Americano",
  "Cocker Spaniel Inglês",
  "Collie",
  "Dachshund",
  "Dálmata",
  "Dandie Dinmont Terrier",
  "Doberman",
  "Dogue Alemão",
  "Dogue",
  "Dogo Argentino",
  "Dogue Canário",
  "Dogue de Bordeaux",
  "Elkhound Norueguês",
  "Fila Brasileiro",
  "Fox Terrier (Pêlo Duro e Pêlo Liso)",
  "Foxhound Inglês",
  "Galgo Escocês",
  "Galgo Irlandês",
  "Golden Retriever",
  "Gos d’Atura",
  "Grande Boiadeiro Suiço",
  "Greyhound",
  "Galgo Inglês",
  "Grifo da Bélgica",
  "Husky Siberiano",
  "Jack Russel Terrier",
  "King Charles",
  "Komondor",
  "Kuvasz",
  "Labradoodle",
  "Labrador Retriever",
  "Laika",
  "Lakeland Terrier",
  "Leonberger",
  "Lhasa Apso",
  "Malamute-do-Alasca",
  "Maltês",
  "Mastife",
  "Mastin dos Pirenéus",
  "Mastin do Tibete",
  "Mastin Espanhol",
  "Mastín Napolitano",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Old English Sheepdog (Bobtail)",
  "Papillon",
  "Pastor Alemão",
  "Pastor Australiano",
  "Pastor Belga",
  "Pastor de Brie",
  "Pastor dos Pirenéus de Cara Rosa",
  "Pequeno Cão Leão",
  "Pequinês",
  "Perdigueiro",
  "Pinscher miniatura",
  "Pitbull",
  "Podengo",
  "Poodle",
  "Pointer",
  "Pug",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Rough Collie",
  "Sabueso (Espanhol ou Italiano)",
  "Saluki",
  "Samoieda",
  "São Bernardo",
  "Scottish Terrier",
  "Setter Irlandés",
  "Shar-Pei",
  "Shiba Inu",
  "Shih Tzu",
  "SilKy Terrier",
  "Skye Terrier",
  "Smooth Collie",
  "Spitz Alemão",
  "Spitz Lobo",
  "Spitz Gigante",
  "Spitz Médio",
  "Spitz Pequeno ",
  "Spitz Anão",
  "Lulu da Pomerânia",
  "Staffordshire Bull Terrier",
  "Tamaskan",
  "Teckel",
  "Terra Nova",
  "Terrier Australiano",
  "Terrier Escocês",
  "Terrier Irlandês",
  "Terrier Japonês",
  "Terrier Negro Russo",
  "Terrier Norfolk",
  "Terrier Norwich",
  "Terrier Tibetano",
  "Tosa",
  "Weimaraner",
  "Welsh Corgi (Cardigan)",
  "Welsh Corgi (Pembroke)",
  "West Highland White Terrier",
  "Whippet",
  "Xoloitzcuintli",
  "Yorkshire Terrier",
];

export const gato: any[] = [
  "Sem Raça Definida (SRD)",
  "Abissínio",
  "Angorá Turco",
  "Asiático de Pêlo Semi-Longo",
  "Azul Russo",
  "Balinês",
  "Bambino",
  "Bicolor Oriental",
  "Bengal",
  "Bobtail americano",
  "Bobtail japonês",
  "Bombay",
  "Burmês ou Birmanês",
  "Burmila",
  "California Spangled",
  "Cingapura",
  "Chartreux",
  "Chausie",
  "Colorpoint de Pêlo Curto",
  "Cornish Rex",
  "Curl Americano",
  "Devon Rex",
  "Donskoy",
  "Dragon Li",
  "Egeu",
  "Exótico Shorthair",
  "Gato de Bengala",
  "Gato do Chipre",
  "Gato Asiático",
  "Gato Siberiano",
  "Havana Marrom",
  "Himalaio",
  "Javanês",
  "Korat",
  "Khao Manee",
  "Kurilian Bobtail",
  "LaPerm",
  "Levkoy Ucraniano",
  "Lykoi",
  "Maine Coon",
  "Manx",
  "Manx de Pêlo Longo",
  "Mau Árabe",
  "Mau Egípcio",
  "MinsKin",
  "Mist Australiano",
  "Munchkin",
  "Nebelung",
  "Norueguês da Floresta",
  "Ocicat",
  "Ojos Azules",
  "Oregon Rex",
  "Pêlo Curto Americano",
  "Pêlo Curto Brasileiro",
  "Pêlo Curto Europeu",
  "Pêlo Curto Inglês ou British Shorthair",
  "Pêlo Longo Inglês",
  "Pêlo Curto Oriental",
  "Pêlo Longo Oriental",
  "Persa",
  "Peterbald",
  "Pixie-bob",
  "Raas",
  "Ragamuffin",
  "Ragdoll",
  "Rex Alemão",
  "Sagrado da Birmânia",
  "Savannah",
  "Scottish Fold",
  "Selkirk Rex",
  "Serengeti",
  "Siamês",
  "Singapura",
  "Snowshoe",
  "Sokoke",
  "Somali",
  "Sphynx",
  "Suphalak",
  "Thai",
  "Tiffany-Chantilly",
  "Tonquinês",
  "Toyger",
  "Usuri",
  "Van Turco",
  "Wirehair Americano",
];
